apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: result
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: "{{ .Values.registry }}/result:{{ .Values.resulttag }}"
        name: result
