apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  ports:
  - name: "result-service"
    port: 5001
    targetPort: 80
  selector:
    app: result
